image: abstruse_node

matrix:
  - env: NODE_VERSION=8

install:
  - nvm install $NODE_VERSION
  - npm install

script:
  - ./scripts/ci/angular.sh
  - ./scripts/ci/build.sh
  - ./test.sh node

cache:
  - node_modules
